version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis_livraison
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7
    container_name: mongo_livraison
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123